spring.application.name=Chess

# Server configuration
server.port=8080
server.servlet.context-path=/

# Security configuration
spring.security.filter.order=10

# CORS configuration
spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*

# WebSocket configuration
spring.websocket.max-text-message-size=8192
spring.websocket.max-binary-message-size=8192

FIREBASE_CONFIG=${FIREBASE_CONFIG}

