services:
  backend:
    image: ghcr.io/iamthejafar/chess-backend:latest
    container_name: chess-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE
      - PORT
      - DB_URL
      - DB_USER
      - DB_PASSWORD
      - REDIS_URL
      - JWT_SECRET
      - APP_CORS_ALLOWED_ORIGINS
      - APP_UPLOAD_DIR